CREATE OR REPLACE PROCEDURE MY_PROC7890("INPUT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LAGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE out VARCHAR;
BEGIN
    out := ''Your Input parameter is '' || input;
    RETURN out;
END;
';

