name: Snowflake Deploy (dev - changed SQL only)

on:
  push:
    branches: [ develop ]
    paths:
      - "SQL_DIR/**/*.sql"
      - ".github/workflows/dev-snowflake-deploy.yml"

env:
  ENV: dev
  SNOWFLAKE_GIT_REPO: git_repo_dev
  SNOWFLAKE_GIT_BRANCH: develop
  SQL_ROOT: SQL_DIR
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]   # change to ubuntu-latest if you prefer
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq + Snowflake CLI + AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip awscli
          python3 -m pip install --user --upgrade "snowflake-cli-labs>=2.0.0"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          snow --version
          aws --version

      - name: Export Snowflake creds from GitHub Secrets (DEV)
        run: |
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USERNAME=${{ secrets.SNOWFLAKE_USERNAME_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_SCHEMA=${{ secrets.SNOWFLAKE_SCHEMA_DEV }}" >> $GITHUB_ENV

      - name: List changed SQL files (range or single commit)
        id: diff
        shell: bash
        run: |
          set -euo pipefail

          if [[ -n "${{ github.event.before }}" && "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
            range="${{ github.event.before }}..${{ github.sha }}"
            pathspec=":(glob)${SQL_ROOT%/}/**/*.sql"
            CHANGED=$(git diff --name-only --diff-filter=ACMR "$range" -- "$pathspec")
          else
            pathspec=":(glob)${SQL_ROOT%/}/**/*.sql"
            CHANGED=$(git diff-tree --no-commit-id --name-only -r "${GITHUB_SHA}" -- "$pathspec")
          fi

          printf "%s\n" "$CHANGED" > changed_files.txt
          CHANGED="${CHANGED//$'\n'/ }"
          echo "changed=${CHANGED}" >> "$GITHUB_OUTPUT"
          echo "Changed SQL:"
          cat changed_files.txt || true

      - name: Build deploy.sql (reference only)
        if: ${{ steps.diff.outputs.changed != '' }}
        shell: bash
        run: |
          set -euo pipefail
          : > deploy.sql

          {
            echo "-- env: ${ENV}"
            echo "USE ROLE ${SNOWFLAKE_ROLE};"
            echo "USE WAREHOUSE ${SNOWFLAKE_WAREHOUSE};"
            echo "USE DATABASE ${SNOWFLAKE_DATABASE};"
            echo "USE SCHEMA ${SNOWFLAKE_SCHEMA};"
            echo "ALTER GIT REPOSITORY ${SNOWFLAKE_GIT_REPO} FETCH;"
          } >> deploy.sql

          # Keep SQL_DIR/ prefix in paths
          while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            rel="${f#./}"
            echo "EXECUTE IMMEDIATE FROM @${SNOWFLAKE_GIT_REPO}/branches/${SNOWFLAKE_GIT_BRANCH}/${rel};"
          done < changed_files.txt >> deploy.sql

          echo "----- deploy.sql -----"
          sed -n '1,200p' deploy.sql

      - name: Exit early (no changed SQL)
        if: ${{ steps.diff.outputs.changed == '' }}
        run: echo "No SQL changes under ${SQL_ROOT}; nothing to deploy."

      # RUN PER-FILE ONLY — NO batch -f deploy.sql here
      - name: Execute each changed SQL & notify via SNS (always succeed)
        if: ${{ steps.diff.outputs.changed != '' }}
        env:
          SNOWFLAKE_AUTHENTICATOR: snowflake
          SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:660061364911:datahub-notifications-sns-topic
        shell: bash
        run: |
          set -uo pipefail  # NOTE: no -e

          # 0) quick identity check (uses env SNOWFLAKE_PASSWORD)
          snow sql \
            -q "SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();" \
            --temporary-connection \
            --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USERNAME" \
            --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" \
            --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" \
            --authenticator "$SNOWFLAKE_AUTHENTICATOR"

          # 1) refresh repo
          snow sql \
            -q "ALTER GIT REPOSITORY ${SNOWFLAKE_GIT_REPO} FETCH;" \
            --temporary-connection \
            --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USERNAME" \
            --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" \
            --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" \
            --authenticator "$SNOWFLAKE_AUTHENTICATOR"

          successes=()
          failures=()
          : > snow_exec_detail.log

          while IFS= read -r f; do
            [[ -z "$f" ]] && continue
            rel="${f#./}"  # preserve SQL_DIR/
            stage="@${SNOWFLAKE_GIT_REPO}/branches/${SNOWFLAKE_GIT_BRANCH}/${rel}"

            echo "---- Executing: ${stage}" | tee -a snow_exec_detail.log
            tmpout="$(mktemp)"
            snow sql \
              -q "EXECUTE IMMEDIATE FROM ${stage};" \
              --temporary-connection \
              --account "$SNOWFLAKE_ACCOUNT" --user "$SNOWFLAKE_USERNAME" \
              --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" \
              --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA" \
              --authenticator "$SNOWFLAKE_AUTHENTICATOR" \
              >"$tmpout" 2>&1
            rc=$?

            cat "$tmpout" >> snow_exec_detail.log
            echo >> snow_exec_detail.log
            if [[ $rc -eq 0 ]]; then
              successes+=("$rel")
            else
              failures+=("$rel")
              echo "ERROR for ${rel}: $(head -n 1 "$tmpout")" | tee -a snow_exec_detail.log
            fi
            rm -f "$tmpout"
          done < changed_files.txt

          ok_count=${#successes[@]}
          fail_count=${#failures[@]}
          status_word=$([[ $fail_count -gt 0 ]] && echo "COMPLETED with FAILURES" || echo "SUCCESS")
          subject="Snowflake deploy (${ENV}) — ${status_word}: ${ok_count} ok / ${fail_count} failed"

          {
            echo "Environment: ${ENV}"
            echo "Database.Schema: ${SNOWFLAKE_DATABASE}.${SNOWFLAKE_SCHEMA}"
            echo "Warehouse: ${SNOWFLAKE_WAREHOUSE}"
            echo
            echo "✅ SUCCEEDED (${ok_count}):"
            (( ok_count )) && printf ' - %s\n' "${successes[@]}" || echo " - (none)"
            echo
            echo "❌ FAILED (${fail_count}):"
            (( fail_count )) && printf ' - %s\n' "${failures[@]}" || echo " - (none)"
            echo
            echo "===== DETAIL ====="
            cat snow_exec_detail.log
          } > sns_message.txt

          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "$subject" \
            --message file://sns_message.txt

          # Always succeed this step so the pipeline stays green
          exit 0

      - name: Upload deploy.sql artifact
        if: ${{ steps.diff.outputs.changed != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: dev-deploy-sql
          path: deploy.sql

      - name: Upload execution detail log
        if: ${{ steps.diff.outputs.changed != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: snowflake-exec-detail
          path: snow_exec_detail.log

