name: PR Checks (auto-merge)

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

# keep runs for PR and PRT separate
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: [self-hosted, Linux, X64]
    permissions: { contents: read, pull-requests: read }
    # ... your existing steps ...

  enable_auto_merge:
    if: github.event_name == 'pull_request_target' && github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    runs-on: [self-hosted, Linux, X64]
    permissions: { contents: write, pull-requests: write }
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            // pick an allowed method (prefer SQUASH)
            const repo = await github.graphql(`
              query($o:String!,$n:String!){repository(owner:$o,name:$n){
                autoMergeAllowed squashMergeAllowed mergeCommitAllowed rebaseMergeAllowed
              }}`, { o: context.repo.owner, n: context.repo.repo });
            if (!repo.repository.autoMergeAllowed) {
              core.warning('Enable "Allow auto-merge" in repository settings.');
              return;
            }
            let method = repo.repository.squashMergeAllowed ? 'SQUASH'
              : repo.repository.mergeCommitAllowed ? 'MERGE'
              : repo.repository.rebaseMergeAllowed ? 'REBASE' : null;
            if (!method) { core.warning('No merge methods enabled.'); return; }
            await github.graphql(`
              mutation($id:ID!,$m:PullRequestMergeMethod!){
                enablePullRequestAutoMerge(input:{pullRequestId:$id, mergeMethod:$m}){clientMutationId}
              }`, { id: pr.node_id, m: method });
            core.notice(`Auto-merge enabled with ${method}.`);
